name: ${PROJECT_NAME}

services:
  mihomo:
    image: ${MIHOMO_IMAGE}
    container_name: mihomo
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ./config:/root/.config/mihomo
      - ./providers:/root/.config/mihomo/providers
      - ./cache:/root/.config/mihomo/cache
      - ./logs:/root/.config/mihomo/logs
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

  zashboard:
    image: ${ZASHBOARD_IMAGE}
    container_name: zashboard
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "${DASHBOARD_PORT}:80"
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

  subconverter:
    image: ${SUBCONVERTER_IMAGE}
    container_name: subconverter
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - MANAGED_CONFIG_PREFIX=http://${HOST_IP}:${SUBCONVERTER_PORT}
    ports:
      - "${SUBCONVERTER_PORT}:25500"
    volumes:
      - ./subconverter/base/pref.toml:/base/pref.toml:ro
      - ./subconverter/stats:/base/stats
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
